### ISSUE TITLE
How to fire tag only if both ad_storage and analytics_storage are granted

### ISSUE THREAD

**Issue by thorewi** [68publishers/cookie-consent#16]
Hello,

some tags like FB pixel are used for both remarketing and analytics (as far as I know). How to setup GTM to fire this tag only if both ad_storage and analytics_storage are granted? Thank you very much and Merry Christmas :)

**Comment by tg666** [comment]
Hello,

This is not possible with the current version but I just [implemented it](https://github.com/68publishers/cookie-consent/pull/17) and released it as a beta version. Can you please try it and tell me if everything is going the way it is?

- [Updated template](https://github.com/68publishers/cookie-consent/blob/feature/combined-storage-consent/gtm_template.tpl)
- Set the version `0.3.0-beta.0` in field `Package version` in a tag configuration
- Configuration for this feature is described in README [here](https://github.com/68publishers/cookie-consent/tree/feature/combined-storage-consent#event-triggers-based-on-composite-consent)

When you tell me everything works as expected then I'll release a new stable version.
Thank you and enjoy the rest of the Xmas holidays :)

**Comment by thorewi** [comment]
Hi,

thank you for such a robust solution! Two things:

1) Tags are not fired until the page is reloaded, on another page, where older version is deployed, it works fine...
2) I think there can be something like 68publishers_ad_analytics_storage event by default as it will be used on common basis... for Facebook pixel, Sklik pixels and so on... now it is just a few clicks, but when you do it for 100+ GTM, you feel it...

**Comment by tg666** [comment]
1. Are you sure? I'm trying it right now and triggers are fired:

https://user-images.githubusercontent.com/24430186/147514429-edcfe2a8-2163-4cf7-a2eb-e0f2a535c447.mov

In the video, the `functionality` and `security` storage are marked as "enabled by default" so their triggers are fired already in the Template's code. `Personalization` storage has no trigger configured.  Triggers for other storages (ad, analytics) and "combined consent" trigger `fb_pixel_test` are fired after the consent without a page reloading. Console messages in the video are logged by tags that are fired with the triggers.

Are you using this version in your configuration (`latest` will not work because the latest stable version is `0.2.7`)?

<img width="301" alt="Snímek obrazovky 2021-12-28 v 1 05 20" src="https://user-images.githubusercontent.com/24430186/147514724-af941188-9dd8-4960-bb9e-06a816daaaeb.png">

2) You are right. I originally had also column `operator` (radio button with values OR, AND) in a Param table that contains triggers for composite consent and removed fields `Event trigger` for all storages - I wanted to configure all triggers in the table.

But I found a problem, I think the is no way how to define default rows for a Param table in GTM. Param tables have an option `Default value` in a "form builder" but I don't know how to define default rows and I didn't find an answer on the internet.

This is the reason why there is not some default event like `68publishers_ad_analytics_storage` and why I kept fields `Event trigger` for each storage separately.

**Comment by thorewi** [comment]
1. you are right, I've changed package version in default values but after that I didn't change it in already created tag, my bad... everything works as it should...
2. hmm... then the question is whether the events "68publishers_ad_analytics_storage", "68publishers_ad_storage", "68publishers_analytics_storage" and so on should not be hardcoded for now... and wait if someone would really need this "composite consent" functionality...

**Comment by tg666** [comment]
I don't think it is a good idea to hardcode any events. For example, we have one project with triggers `consent_necessary` (triggered by `functionality_storage`, the `security_storage` is synchronized with the functionality storage) and `consent_marketing` (triggered by the `analytics_storage`) only.
Thus the only two triggers with custom names are configured and ofc we don't need any `68publishers_ad_analytics_storage`.

Btw. if you have a lot of projects in GTM with some common configuration you can configure only one of them with the common options and then "Export container", select the template, tag, triggers and you receive JSON that can be imported (with `merge` strategy) into GTM of another project. That's the way we do it.

**Comment by thorewi** [comment]
Ok, let's merge it.

Thank you for the great tip!
