### ISSUE TITLE
What to do with alrady saved cookies?

### ISSUE THREAD

**Issue by thorewi** [68publishers/cookie-consent#20]
Hello,

what to do with cookies already saved before the "Cookie consent"? I guess I should delete them all together with first display of the Cookie Consent bar, right? Is there a way how to achieve this with this plugin? 

Thank you.

**Comment by jelen07** [comment]
Hi Tomáš, do you have any legal basis for your assumptions? I would just like to remind you that the change from 1.1.2022 in the Czech Republic concerns the change from opt-in to opt-out.

**Comment by thorewi** [comment]
No, I don't. And you probably meant the change from opt-out to opt-in, right? 

But if you have already saved some analytics/marketing cookies according to opt-out principle, do you still display this new cookie consent widget?

**Comment by jelen07** [comment]
Yeah, you're right - to opt-in (fixed in the previous comment).

It depends... UC:
1. User has analytics cookies stored before 1.1.2022
2. After 1.1.2022 your application doesn't use that analytics cookies without consent
3. User accept the consent and your app start using analytics

I guess, that this could be a valid scenario regardless of whether the legal change is just about storing the cookie files.
Definitely need to be checked with the legal department.

**Comment by thorewi** [comment]
Hm, to be honest, I'm not sure if I understand your use case correctly. But it seems logical, that if someone gave you the "opt-out" consent in the past, you don't have to display him the "opt-in" consent bar.

However, the problem at least on our websites is there was no "opt-out" cookie consent bar and therefore we don't have any stored cookie, from which I would know that I have already received the "opt-out" consent (ie. the visitor already visited my websites before). So I would rather display the new "opt-in" cookie consent bar always.

We can leave the issue open for some time and then close it.
