### ISSUE TITLE
What needs to be done when a new version is released

### ISSUE THREAD

**Issue by thorewi** [68publishers/cookie-consent#25]
Hi,

when you release a new version, what do I need to do to properly update it in my GTM? In "Cookie Consent" tag, package version is set to "latest". I need to download and reimport gtm_template.tpl and do I need to do something with "Cookie Consent" tag itself? Thank you.

**Comment by thorewi** [comment]
I'm asking because I have a tag fired on "Window Loaded" event and in this tag I have `console.log(CookieConsentWrapper);` and sometimes I get "CookieConsentWrapper is not defined" error. I tried to set "Package version" in "Cookie Consent" tag to "0.3.1" to be sure I have a latest version, but it didn't help.

**Comment by thorewi** [comment]
Thank you for the great job, but still I think it doesn't solve my problem. I have a Sklik plugin like this:

<img width="1200" alt="Screenshot 2022-01-03 at 8 07 12" src="https://user-images.githubusercontent.com/605858/147906317-c89ddc6a-c876-4269-950d-37ba5a99bcd1.png">

and I need the 'ad_analytics_storage_allowed' variable to be already set. I can't wrap it to a callback. Wouldn't it be better to have the entire cookie-consent.min.js content right in the template without injectScript? Then everything would be synchronous, independent of unpkg.com availability and probably more "stable" (now if I have set Package version to "latest" I will get always the latest version from unpkg.com even without updating the plugin?)

**Comment by tg666** [comment]
> when you release a new version, what do I need to do to properly update it in my GTM? In "Cookie Consent" tag, package version is set to "latest". I need to download and reimport gtm_template.tpl and do I need to do something with "Cookie Consent" tag itself? Thank you.

If you wanna update to the newer version then you must look into a release and you must reimport the Template in your GTM if the Template has been modified.
Just open the `Cookie Consent` Template, click on three dots (right dropdown menu) and import it. Everything will be updated but your existing configurations inside tags will be kept.
I recommend locking `Package version` and avoid of using `latest` release because it's may not be compatible with your (probably old) template. So when the new version will be released look into changes and update the Template if needed + update `Package version`. If the template is still the same between versions then update only `Package version`.

> I'm asking because I have a tag fired on "Window Loaded" event and in this tag I have console.log(CookieConsentWrapper); and sometimes I get "CookieConsentWrapper is not defined" error. I tried to set "Package version" in "Cookie Consent" tag to "0.3.1" to be sure I have a latest version, but it didn't help.

You're right, I tried it, and it really happened sometimes. Sometimes the wrapper was created in the `window` later and wasn't accessible. If you need to access the wrapper directly in JavaScript you must paste your logic into the event `init`. The method `CookieConsentWrapper.on()` is now accessible in all page triggers (Page view, DOM Loaded, Window loaded). Viz. [README](https://github.com/68publishers/cookie-consent#accessing-the-wrapper-in-the-javascript).

This "fix" will be also available in the version `0.3.2`.

And to that last thing,
the logic that resolves consent with the storages is already in the Template and independent from the wrapper (and unpkg.com). The wrapper only configures the original plugin (with all the additional features) and ensures consent changes.

But the whole package don't works with variables but with custom triggers. If you define this trigger:

<img width="935" alt="Snímek obrazovky 2022-01-03 v 9 31 42" src="https://user-images.githubusercontent.com/24430186/147911508-47769ff8-8189-4155-a86c-14ee8829c24f.png">

<img width="883" alt="Snímek obrazovky 2022-01-03 v 9 32 59" src="https://user-images.githubusercontent.com/24430186/147911597-d3eefb85-8b23-48fa-8b2a-5cbcdaedc22a.png">

And associate this trigger with your tag instead of that `Page view` trigger (and also now you don't need the `{{ad_analytics_storage_allowed}}` variable), then it should works.

Calling of the trigger will be invoked directly from the Template if the user already makes consent with `ad` and `analytics` storages. And if not, then will be the trigger called from the wrapper at the moment when the user makes the consent.

**Comment by thorewi** [comment]
Thanks for great explanation. But using ad_analytics_storage_enabled event will fire the tag only if the consent was given. But I want to fire the tag always, just with different settings... For Sklik, the code is this:

```
<script type="text/javascript" src="https://c.seznam.cz/js/rc.js"></script>
<script>
var conversionConf = {
  id: 10000000, /* identifikátor konverze Sklik*/
  value: 199.9, /* hodnota objednávky v Kč*/
  orderId: 123456, /* identifikátor objednávky Zboží.cz*/
  zboziType: “standard”, /* “standard” (standardní měření), “limited” (omezené měření), nebo “sandbox” měření konverzí Zboží.cz */
  zboziId: “QQQQ”,  /* ID provozovny Zboží.cz*/
  consent: 1 /* souhlas od návštěvníka na odeslání konverzního hitu, povolené hodnoty: 0 (není souhlas) nebo 1 (je souhlas) */
};
 // Ujistěte se, že metoda existuje, předtím než ji zavoláte
 if (window.rc && window.rc.conversionHit) {
   window.rc.conversionHit(conversionConf);
 }
</script>
```

where you can see property "consent" which I want to set dynamically.

**Comment by tg666** [comment]
Now I understand ... hm ... I think you can read it directly from the cookie:

<img width="1203" alt="Snímek obrazovky 2022-01-03 v 10 31 01" src="https://user-images.githubusercontent.com/24430186/147916032-3a36e938-7151-4d34-baaf-804ef3fc78da.png">

<img width="1163" alt="Snímek obrazovky 2022-01-03 v 10 31 20" src="https://user-images.githubusercontent.com/24430186/147916047-0a467b9b-84a0-4d1a-9dae-770924ed60d4.png">

Now will be your variable `{{ad_analytics_storage_allowed}}` ready to use.

**Comment by thorewi** [comment]
yeah I had the same idea just wanted to ask if there is a better way... thank you very much...
