### ISSUE TITLE
GCM v2.0 (additional consents)

### ISSUE THREAD

**Issue by tomasz-wnuk** [68publishers/cookie-consent#63]
When do you plan to implement GCM v2.0?
ad_user_data 
ad_personalization

New DMA regulations starts from 03'24

**Comment by jelen07** [comment]
We are going to publish a new version in the first half of February. You will be able to deploy the new version to your website and apps ahead of time so that everything is as it should be by March 1.

**Comment by Fumping** [comment]
@jelen07 do you already have a exact ETA?

**Comment by Yorgv** [comment]
Any updates on this?

**Comment by tomasz-wnuk** [comment]
Please, let us know, Is it worth waiting for the new version of CC'68? or changing cookie consent. GAds will stop on 01/03/24

**Comment by Oynowan** [comment]
I would like to know too. I was looking lately for cookieconsent and that one looks good, only needs update.

**Comment by jelen07** [comment]
The new GCMv2 is already implemented. Since Feb 19, see https://github.com/68publishers/cookie-consent/tree/feature/gcm2.

The production tests were great, you can start using it now. The release will be soon.

**Comment by tg666** [comment]
The changes have been already released under the version `0.5.0`.
Due to the limits of GTM templates, configuration changes have been made. Please pay attention to the [documentation](https://github.com/68publishers/cookie-consent/blob/main/docs/migration-from-0.4-to-0.5.md).

I would like to point out that we are missing translations for the new keys `ad_user_data_title`, `ad_user_data_description`, `ad_personalization_title` and `ad_personalization_description`.

If you would like to display these new storages in the cookie bar and have some meaningful translations, PR would be appreciated.
